### ISSUE TITLE
Unclear why this is necessary

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/xPendingReboot#23]
It is unclear in the docs why this resource is needed.  Setting `$global:DSCMachineStatus = 1` in a script resource without using xPendingReboot will still cause the machine to reboot.  Could you please describe the default case (where `$global:DSCMachineStatus = 1` is set without xPendingReboot) and what value xPendingReboot provides over the default case?

**Comment by Jaykul** [comment]
I believe the point of xPendingReboot is to set `$global:DSCMachineStatus = 1` _if_ any of the three registry locations indicate that a reboot is needed -- regardless of whether the DSC needs a reboot otherwise...
