### ISSUE TITLE
Move this resource to ComputerManagementDsc

### ISSUE THREAD

**Issue by johlju** [PowerShell/xPendingReboot#27]
In https://github.com/PowerShell/DscResources/issues/374 there are a proposal to move this resource over to the module ComputerManagementDsc, it would be a good opportunity to make breaking changes (fixing open issues) and making it more HQRM.

@bcwilhite or @nehrua what are your thoughts on this? Is this something already being worked on?

**Comment by nehrua** [comment]
I don't think this is in the works, but I'll defer to Brian for confirmation.  I do think its a good fit for ComputerManagementDsc.

**Comment by PlagueHO** [comment]
This is now in progress over in ComputerManagementDsc.

**Comment by PlagueHO** [comment]
This has been completed. I'll raise a PR to this repo to mark it as deprecated (similar to xTimezone: https://github.com/PowerShell/xTimeZone).
