### ISSUE TITLE
How can I make sure this runs last

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xPendingReboot#3]
I want to make sure this runs last when doing the configuration.

**Comment by iainbrighton** [comment]
@AceHack In that case you'll need to add a `DependsOn` statement to the `xPendingReboot` configuration and specify all resources that you need to have run first.

**Comment by AceHack** [comment]
So I have many conditional resources that get included based on cofing data, there are also about 10 other things that this could depend on.  I was hoping for a better way to make something run last.  Thanks.

**Comment by iainbrighton** [comment]
@AceHack Unfortunately, it's the Local Configuration Manager (LCM) that is responsible for executing each resource. The only way to control any order is with dependencies - resources themselves have no way of controlling this.

**Comment by dragon788** [comment]
@AceHack are you using Partial Configurations to determine the conditional resources or some other means of aggregating all the roles/IDs?

**Comment by ChrisLGardner** [comment]
Assuming you're using If statements to limit which resources get run then you could do something like this:

```
$PendingRebootDependsOn = @()
if ($SomeCondition) {
    SomeResource Name{
    }
    $PendingRebootDependsOn += "[SomeResource]Name"
}

xPendingReboot FinalReboot {
    Name = "Final Reboot"
    DependsOn = $PendingRebootDependsOn
}
```

**Comment by johlju** [comment]
Closing this as solved as per previous comments. Please reopen or comment if this was closed in error.

**Comment by AceHack** [comment]
@johlju this was not solved, it cannot be done with current design without very complex depends on rules.  There is no simple way to have something run last.

**Comment by johlju** [comment]
I meant solved as in the solution provided in previous comment is the way to do it, maybe answered would have been a better word. :) There is a user voice item for this here [Ability to run a DSC configuration item last](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15675876-ability-to-run-a-dsc-configuration-item-last). Vote on it and maybe that will be an improvement in a future LCM.
