### ISSUE TITLE
CCM_ClientUtilities warning on every run

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xPendingReboot#4]
WARNING: [RAL-DEV-AGENT]:                            [[xPendingReboot]Reboot1] Unable to query CCM_ClientUtilities: Invalid namespace

**Comment by VAsHachiRoku** [comment]
Same I tried to use the SkipCcmClientSDK = $True, but this did remove the warning.

**Comment by VAsHachiRoku** [comment]
Just tested after pulling down the latest version and issue still seems to be there. I'm running version 0.2.0.0. Just want to validate I am using the correct one.

**Comment by TravisEz13** [comment]
This was introduced in Version 0.2.34.0 You can manually get it from the test [artifacts](https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.2.34.0/artifacts)

or there are instructions on installing [development builds here](https://github.com/PowerShell/DscResources#development-builds)
