### ISSUE TITLE
Registry key evaluation not always working

### ISSUE THREAD

**Issue by PiAnAnXa** [PowerShell/xPendingReboot#8]
Due to a missing \ after hklm: the Component Based Servicing and Windows Update keys are not always processed I believe.
Problem code in MSFT_xPendingReboot.psm1 @ line 14 & 24

**Comment by peppekerstens** [comment]
@PiAnAnXa  & @kwirkykat 
Double checked xPendingReboot code.  @PiAnAnXa is correct as far is code is concerned;
_current_ behavior (PowerShell 5 and earlier versions) of Get-ChildItem dictates a "Windows style path" (https://en.wikipedia.org/wiki/Path_(computing)#MS-DOS.2FMicrosoft_Windows_style) like path, so hlkm:\ or c:\
see: https://technet.microsoft.com/en-us/library/ee176841.aspx
and: https://technet.microsoft.com/en-us/library/hh849800.aspx

**Comment by PlagueHO** [comment]
I think this issue has been resolved and can be closed.

**Comment by PlagueHO** [comment]
@gaelcolas - can you close this one?
